// <auto-generated />
using System;
using BecasApi.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BecasApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230126060618_Becas")]
    partial class Becas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BecasApi.Entidades.Alumno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<bool>("Genero")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Alumnos");
                });

            modelBuilder.Entity("BecasApi.Entidades.Becas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Becas");
                });

            modelBuilder.Entity("BecasApi.Entidades.BecasAlumnos", b =>
                {
                    b.Property<int>("BecaId")
                        .HasColumnType("int");

                    b.Property<int>("AlumnoId")
                        .HasColumnType("int");

                    b.Property<int?>("BecasId")
                        .HasColumnType("int");

                    b.HasKey("BecaId", "AlumnoId");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("BecasId");

                    b.ToTable("BecasAlumnos");
                });

            modelBuilder.Entity("BecasApi.Entidades.BecasAlumnos", b =>
                {
                    b.HasOne("BecasApi.Entidades.Alumno", "Alumno")
                        .WithMany("BecasAlumnos")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BecasApi.Entidades.Becas", "Becas")
                        .WithMany("BecasAlumnos")
                        .HasForeignKey("BecasId");

                    b.Navigation("Alumno");

                    b.Navigation("Becas");
                });

            modelBuilder.Entity("BecasApi.Entidades.Alumno", b =>
                {
                    b.Navigation("BecasAlumnos");
                });

            modelBuilder.Entity("BecasApi.Entidades.Becas", b =>
                {
                    b.Navigation("BecasAlumnos");
                });
#pragma warning restore 612, 618
        }
    }
}
